### ISSUE TITLE
Broken when Shadow DOM enabled

### ISSUE THREAD

**Issue by differentmatt** [muchweb/atom-neon-selection#3]
This package used to work well, but I don't see the neon selection anymore in Atom 0.172.0.  This might not be the exact Atom version that neon selection stopped working.

Using Atom Dark theme:
![screen shot 2015-01-15 at 9 37 54 am](https://cloud.githubusercontent.com/assets/2965172/5762839/3a407fa2-9c9a-11e4-9f5c-6ee0730307f6.png)

**Comment by muchweb** [comment]
Thank you. I suspect this is because 'Shadow DOM' is now enabled by default.

**Comment by differentmatt** [comment]
Yes, I've confirmed unchecking 'Use Shadow DOM' fixes this problem.
