### ISSUE TITLE
Deprecated selector in `neon-selection/styles/neon-selection.atom-text-editor.less`

### ISSUE THREAD

**Issue by zzeroo** [muchweb/atom-neon-selection#9]
In `neon-selection/styles/neon-selection.atom-text-editor.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `.editor .selection .region,
atom-text-editor .selection .region,
:host .selection .region` => `.editor .selection .region,
atom-text-editor .selection .region,atom-text-editor .selection .region`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by Jerajo** [comment]
Fixed in #13.

**Comment by zzeroo** [comment]
Ok can confirm that.
